"""create initial tables

Revision ID: c0d704fe1f40
Revises: 
Create Date: 2026-01-08 08:48:45.859956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c0d704fe1f40'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conversations', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_index(op.f('idx_conversations_user_id'), table_name='conversations')
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.add_column('messages', sa.Column('attachments', sa.Text(), nullable=True))
    op.drop_index(op.f('idx_messages_conversation_id'), table_name='messages')
    op.drop_index(op.f('idx_messages_user_id'), table_name='messages')
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.drop_constraint(op.f('messages_user_id_users_id_fk'), 'messages', type_='foreignkey')
    op.drop_column('messages', 'user_id')
    op.add_column('user_tokens', sa.Column('provider', sa.String(length=50), nullable=False))
    op.add_column('user_tokens', sa.Column('access_token', sa.Text(), nullable=False))
    op.add_column('user_tokens', sa.Column('refresh_token', sa.Text(), nullable=True))
    op.alter_column('user_tokens', 'user_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=False,
               postgresql_using='user_id::uuid')
    op.alter_column('user_tokens', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('user_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('user_tokens', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_index(op.f('idx_user_tokens_created_at'), table_name='user_tokens')
    op.drop_index(op.f('idx_user_tokens_email'), table_name='user_tokens')
    op.drop_index(op.f('idx_user_tokens_user_id'), table_name='user_tokens')
    op.drop_index(op.f('ix_user_tokens_email'), table_name='user_tokens')
    op.drop_index(op.f('ix_user_tokens_user_id'), table_name='user_tokens')
    op.create_index(op.f('ix_user_tokens_user_id'), 'user_tokens', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_tokens_provider'), 'user_tokens', ['provider'], unique=False)
    op.create_foreign_key(None, 'user_tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('user_tokens', 'encrypted_token')
    op.drop_column('user_tokens', 'name')
    op.drop_column('user_tokens', 'email')
    op.add_column('users', sa.Column('image', sa.Text(), nullable=True))
    op.alter_column('users', 'google_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_index(op.f('idx_users_email'), table_name='users')
    op.drop_constraint(op.f('users_email_unique'), 'users', type_='unique')
    op.drop_constraint(op.f('users_google_id_unique'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.drop_column('users', 'calendar_permission_granted')
    op.drop_column('users', 'google_access_token')
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'google_token_expires_at')
    op.drop_column('users', 'google_refresh_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('google_refresh_token', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('google_token_expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('avatar_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('google_access_token', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('calendar_permission_granted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_google_id_unique'), 'users', ['google_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_email_unique'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=False)
    op.alter_column('users', 'google_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('users', 'image')
    op.add_column('user_tokens', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('user_tokens', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('user_tokens', sa.Column('encrypted_token', postgresql.BYTEA(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_tokens', type_='foreignkey')
    op.drop_index(op.f('ix_user_tokens_provider'), table_name='user_tokens')
    op.drop_index(op.f('ix_user_tokens_user_id'), table_name='user_tokens')
    op.create_index(op.f('ix_user_tokens_user_id'), 'user_tokens', ['user_id'], unique=True)
    op.create_index(op.f('ix_user_tokens_email'), 'user_tokens', ['email'], unique=False)
    op.create_index(op.f('idx_user_tokens_user_id'), 'user_tokens', ['user_id'], unique=False)
    op.create_index(op.f('idx_user_tokens_email'), 'user_tokens', ['email'], unique=False)
    op.create_index(op.f('idx_user_tokens_created_at'), 'user_tokens', ['created_at'], unique=False)
    op.alter_column('user_tokens', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('user_tokens', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('user_tokens', 'expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('user_tokens', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('user_tokens', 'refresh_token')
    op.drop_column('user_tokens', 'access_token')
    op.drop_column('user_tokens', 'provider')
    op.add_column('messages', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('messages_user_id_users_id_fk'), 'messages', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.create_index(op.f('idx_messages_user_id'), 'messages', ['user_id'], unique=False)
    op.create_index(op.f('idx_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.drop_column('messages', 'attachments')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.create_index(op.f('idx_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.alter_column('conversations', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
